# -*- coding: utf-8 -*-
"""OSM_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bzBqPEvCjBklgnoE1LqhEcQaNk-laAx

RWANDA FIRM ACTIVITY TRACKER - OSM DATA PIPELINE

This notebook extracts business/firm data from OpenStreetMap for Kigali, Rwanda, cleans it, and saves to Google Drive.
Author: [BeeKayKoozie]
Date: 2026-04

Setup & Drive Mount
"""

# Mount Google Drive and define project paths
from google.colab import drive
drive.mount('/content/drive')

PROJECT_PATH = "/content/drive/MyDrive/rwanda-nightlights-firm-activity"
import os
os.makedirs(f"{PROJECT_PATH}/data/raw", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/data/processed", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/outputs/maps", exist_ok=True)
print("Project directories ready.")

"""Install Required Libraries"""

!pip install -q rasterio geopandas earthengine-api geemap osmnx folium scikit-learn matplotlib seaborn

import ee
import geemap
import geopandas as gpd
import pandas as pd
import numpy as np
import rasterio
from rasterio.mask import mask
from shapely.geometry import mapping
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import folium
from folium.plugins import MarkerCluster

# Authenticate Earth Engine (only once per session)
ee.Authenticate()
ee.Initialize(project='nightlights-project-123456')  # Replace with your GEE project ID
print("Earth Engine initialized.")

"""Download Rwanda Administrative Boundary (Shapefile)
Instead of manual bounding box, we'll use a proper shapefile from GEE or a public source. Here we fetch Rwanda's boundary from FAO GAUL dataset.
"""

# Get Rwanda boundary from FAO GAUL (level 0)
rwanda = ee.FeatureCollection("FAO/GAUL/2015/level0") \
           .filter(ee.Filter.eq('ADM0_NAME', 'Rwanda'))
# Convert to GeoJSON and then to a Shapely geometry
geojson = rwanda.getInfo()
gdf_rwanda = gpd.GeoDataFrame.from_features(geojson['features'])
# Save for later use
gdf_rwanda.to_file(f"{PROJECT_PATH}/data/processed/rwanda_boundary.geojson", driver='GeoJSON')
print("Rwanda boundary saved.")

"""Download Multi‑Year VIIRS Nightlights (2014–2023) and Clip to Rwanda"""

# Section 4: Download Available VIIRS Nightlights and Clip to Rwanda

# Use the correct VIIRS annual collection
# Note: VIIRS Annual V22 has data from 2012 onwards, but we need to filter by system:time_start
collection = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG")
#ee.ImageCollection("NOAA/VIIRS/DNB/ANNUAL_V22")


# Get available years by extracting from system:time_start
def get_year_from_image(img):
    year = ee.Date(img.get('system:time_start')).get('year')
    return img.set('year', year)

collection_with_year = collection.map(get_year_from_image)
available_years = collection_with_year.aggregate_array('year').distinct().sort().getInfo()
print(f"Available years in VIIRS V22 collection: {available_years}")

# Filter to years we want (2015-2023)
years = [y for y in available_years if 2015 <= y <= 2026] if available_years else [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
print(f"Processing years: {years}")

yearly_stats = []

for year in years:
    print(f"\nProcessing year {year}...")

    # Filter by year using system:time_start
    start_date = f"{year}-01-01"
    end_date = f"{year}-12-31"

    img = collection.filterDate(start_date, end_date).first()

    if img is None:
        print(f"  No image found for {year}, skipping.")
        continue

    # Select the 'avg_rad' band (VIIRS uses avg_rad, not 'average')
    band_name = img.bandNames().getInfo()[0] if img.bandNames().getInfo() else 'avg_rad'
    img_avg = img.select(band_name)
    img_clipped = img_avg.clip(rwanda)

    # Export to Drive as GeoTIFF
    out_tif = f"{PROJECT_PATH}/data/raw/nightlights_{year}.tif"

    try:
        geemap.ee_export_image(
            img_clipped,
            filename=out_tif,
            scale=500,
            region=rwanda.geometry(),
            file_per_band=False
        )
        print(f"  Saved {out_tif}")
    except Exception as e:
        print(f"  Error exporting {year}: {e}")
        continue

    # Compute mean nightlights value for Rwanda
    try:
        stats = img_clipped.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=rwanda.geometry(),
            scale=500,
            maxPixels=1e9
        )
        mean_val = stats.get(band_name).getInfo()
        yearly_stats.append({'year': year, 'mean_nightlights': mean_val})
        print(f"  Mean nightlights: {mean_val:.4f}")
    except Exception as e:
        print(f"  Error computing stats for {year}: {e}")
        yearly_stats.append({'year': year, 'mean_nightlights': np.nan})

# Save yearly summary
pd.DataFrame(yearly_stats).to_csv(f"{PROJECT_PATH}/data/processed/yearly_nightlights_summary.csv", index=False)
print("\nYearly summary saved.")

"""Load Firm Locations (from Existing OSM Data or Re‑extract)
Since we already saved kigali_firms_clean.csv, we'll load it. If not present, we can re‑extract using OSMnx.
"""

# Load clean firm data
firms_csv = f"{PROJECT_PATH}/data/processed/kigali_firms_clean.csv"
if not os.path.exists(firms_csv):
    # If missing, re-run OSM extraction (as in original notebook)
    import osmnx as ox
    place = "Kigali, Rwanda"
    tags = {"amenity": True, "shop": True, "office": True}
    gdf = ox.features.features_from_place(place, tags)
    for col in ["name", "amenity", "shop", "office"]:
        if col not in gdf.columns:
            gdf[col] = None
    gdf = gdf[["name", "amenity", "shop", "office", "geometry"]].copy()
    gdf = gdf[gdf["geometry"].notnull()]
    gdf = gdf[gdf[["amenity", "shop", "office"]].notnull().any(axis=1)]
    gdf["type"] = gdf["amenity"].fillna(gdf["shop"]).fillna(gdf["office"])
    firm_types = ["bank", "restaurant", "cafe", "bar", "pharmacy", "supermarket", "shop"]
    gdf = gdf[gdf["type"].isin(firm_types)]
    gdf = gdf[["type", "geometry"]]
    # Get centroids
    gdf_proj = gdf.to_crs(epsg=3857)
    centroids = gdf_proj.centroid.to_crs(epsg=4326)
    gdf["lat"] = centroids.y
    gdf["lon"] = centroids.x
    gdf["activity_score"] = 1
    # Save
    gdf.to_csv(firms_csv, index=False)
    firms_df = gdf
else:
    firms_df = pd.read_csv(firms_csv)
    # Convert back to GeoDataFrame
    firms_df['geometry'] = gpd.points_from_xy(firms_df.lon, firms_df.lat)
    firms_gdf = gpd.GeoDataFrame(firms_df, geometry='geometry', crs="EPSG:4326")

print(f"Loaded {len(firms_df)} firms.")

"""Spatial Join – Assign Nightlights Values to Each Firm for Each Year
We will open each year's GeoTIFF, extract the pixel value at each firm's location, and compile a panel dataset.
"""

# Initialize a list to store firm-year observations
firm_year_data = []

for year in years:
    tif_path = f"{PROJECT_PATH}/data/raw/nightlights_{year}.tif"
    if not os.path.exists(tif_path):
        continue
    with rasterio.open(tif_path) as src:
        # Extract values at firm coordinates
        coords = [(lon, lat) for lon, lat in zip(firms_df.lon, firms_df.lat)]
        values = list(src.sample(coords))
        nightlights_vals = [v[0] if v[0] > 0 else 0 for v in values]  # clip negatives

    temp_df = firms_df.copy()
    temp_df['year'] = year
    temp_df['nightlights'] = nightlights_vals
    firm_year_data.append(temp_df)

# Combine into one DataFrame
firm_panel = pd.concat(firm_year_data, ignore_index=True)
firm_panel.to_csv(f"{PROJECT_PATH}/data/processed/firm_nightlights_panel.csv", index=False)
print("Firm‑level panel dataset created.")

"""K‑Means Clustering to Detect Firm Clusters
We'll cluster firms based on their geographic coordinates and, optionally, their nightlights intensity.
"""

# Prepare data for clustering: lon, lat, and average nightlights (or latest year)
# For simplicity, use coordinates only first
coords = firms_df[['lon', 'lat']].values

# Determine optimal number of clusters using elbow method (quick)
inertias = []
K_range = range(1, 11)
for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(coords)
    inertias.append(kmeans.inertia_)

plt.figure(figsize=(8,4))
plt.plot(K_range, inertias, 'bo-')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method for K‑Means')
plt.savefig(f"{PROJECT_PATH}/outputs/maps/elbow_plot.png")
plt.show()

# Choose k=3 (or based on elbow) and fit
k = 3
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
firms_df['cluster'] = kmeans.fit_predict(coords)

# Save clustered firms
firms_df.to_csv(firms_csv.replace('.csv', '_clustered.csv'), index=False)
print("Clustering complete. Cluster labels added.")

"""Time Series Analysis & Visualization
Plot the average nightlights for each cluster over time and create an interactive map.
"""

# Merge cluster labels with panel data
panel = pd.read_csv(f"{PROJECT_PATH}/data/processed/firm_nightlights_panel.csv")
clusters = firms_df[['lon', 'lat', 'cluster']].drop_duplicates()
panel = panel.merge(clusters, on=['lon', 'lat'], how='left')

# Aggregate mean nightlights per cluster per year
cluster_trend = panel.groupby(['year', 'cluster'])['nightlights'].mean().reset_index()

# Plot
plt.figure(figsize=(10,6))
for clus in sorted(cluster_trend['cluster'].unique()):
    subset = cluster_trend[cluster_trend['cluster']==clus]
    plt.plot(subset['year'], subset['nightlights'], marker='o', label=f'Cluster {clus}')
plt.xlabel('Year')
plt.ylabel('Average Nightlights')
plt.title('Nightlights Trend by Firm Cluster')
plt.legend()
plt.grid(True)
plt.savefig(f"{PROJECT_PATH}/outputs/maps/cluster_trends.png")
plt.show()

# Create a folium map with firms colored by cluster
m = folium.Map(location=[-1.95, 30.06], zoom_start=12)
colors = ['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige', 'darkblue', 'darkgreen']
for _, row in firms_df.iterrows():
    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=4,
        color=colors[row['cluster'] % len(colors)],
        fill=True,
        fill_opacity=0.7,
        popup=f"Type: {row['type']}<br>Cluster: {row['cluster']}"
    ).add_to(m)
m.save(f"{PROJECT_PATH}/outputs/maps/firm_clusters_map.html")
print("Map saved.")

# Section 9: Simulate Survey Data and Merge

# Ensure firms_df exists
if 'firms_df' not in dir():
    firms_csv = f"{PROJECT_PATH}/data/processed/kigali_firms_clean.csv"
    if os.path.exists(firms_csv):
        firms_df = pd.read_csv(firms_csv)
        print(f"Loaded {len(firms_df)} firms from {firms_csv}")
    else:
        print("Firms data not found. Run Section 5 first.")
        firms_df = pd.DataFrame(columns=['type', 'lat', 'lon', 'activity_score'])

if len(firms_df) > 0:
    np.random.seed(42)

    # Create a unique ID column directly
    firms_df_copy = firms_df.copy()
    firms_df_copy['firm_id'] = range(len(firms_df_copy))

    # Simulate survey data using the same firm_id
    survey_df = pd.DataFrame({
        'firm_id': range(len(firms_df_copy)),
        'revenue_estimate': np.random.lognormal(mean=10, sigma=1, size=len(firms_df_copy)),
        'employee_count': np.random.poisson(lam=5, size=len(firms_df_copy)),
        'years_in_operation': np.random.randint(1, 20, size=len(firms_df_copy))
    })

    # Merge directly on firm_id
    merged = firms_df_copy.merge(survey_df, on='firm_id')

    # Save merged dataset
    merged.to_csv(f"{PROJECT_PATH}/data/processed/firms_with_survey_sim.csv", index=False)

    print(f"Simulated survey merge complete.")
    print(f"Firms: {len(firms_df_copy)}, Merged: {len(merged)}")
    print(f"\nSample of merged data:")
    print(merged[['firm_id', 'type', 'revenue_estimate', 'employee_count']].head())
else:
    print("No firms data available to merge.")

# Print key statistics
print("===== PROJECT SUMMARY =====")
print(f"Number of firms: {len(firms_df)}")
print(f"Years covered: {years[0]}-{years[-1]}")
print("\nCluster sizes:")
print(firms_df['cluster'].value_counts().sort_index())
print("\nMean nightlights by cluster (latest year):")
latest_year = panel[panel['year']==years[-1]]
print(latest_year.groupby('cluster')['nightlights'].mean())

"""DiD analysis trial"""

# Simulate a "treatment" - firms in Cluster 1 received an intervention in 2023
panel['treated'] = (panel['cluster'] == 1).astype(int)
panel['post'] = (panel['year'] == 2023).astype(int)
panel['did'] = panel['treated'] * panel['post']

# Basic DiD regression (can export to Stata)
import statsmodels.formula.api as smf
model = smf.ols('nightlights ~ treated + post + did', data=panel).fit()
print(model.summary())

"""Create a firm-level productivity proxy
Combine nightlights with simulated revenue
"""

# Load merged survey data
merged = pd.read_csv(f"{PROJECT_PATH}/data/processed/firms_with_survey_sim.csv")

# Create productivity proxy (revenue per employee)
merged['productivity_proxy'] = merged['revenue_estimate'] / merged['employee_count']

# First, add firm_id to panel by matching on lat/lon (unique firm identifier)
# Create a mapping from lat/lon to firm_id using the merged dataset
firm_id_map = merged[['lat', 'lon', 'firm_id']].drop_duplicates()

# Merge firm_id into panel
panel_with_id = panel.merge(firm_id_map, on=['lat', 'lon'], how='left')

# Now merge the revenue and productivity data
panel_with_revenue = panel_with_id.merge(
    merged[['firm_id', 'revenue_estimate', 'productivity_proxy', 'employee_count', 'years_in_operation']],
    on='firm_id',
    how='left'
)

# Correlation between nightlights and productivity
correlation = panel_with_revenue['nightlights'].corr(panel_with_revenue['productivity_proxy'])
print(f"Correlation (nightlights ~ productivity): {correlation:.3f}")

# Additional analysis: nightlights vs revenue
correlation_rev = panel_with_revenue['nightlights'].corr(panel_with_revenue['revenue_estimate'])
print(f"Correlation (nightlights ~ revenue): {correlation_rev:.3f}")

# By cluster
print("\nCorrelation by cluster:")
for clus in panel_with_revenue['cluster'].dropna().unique():
    subset = panel_with_revenue[panel_with_revenue['cluster'] == clus]
    corr = subset['nightlights'].corr(subset['productivity_proxy'])
    print(f"  Cluster {int(clus)}: {corr:.3f}")

# Save the enriched panel
panel_with_revenue.to_csv(f"{PROJECT_PATH}/data/processed/panel_with_revenue.csv", index=False)
print(f"\nEnriched panel saved with {len(panel_with_revenue)} observations")
print(f"Columns: {list(panel_with_revenue.columns)}")